In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/properties.csv")

In [3]:
df.head()

,id,title,price,price_display,price_per_sqft,locality,city,bhk,bathrooms,balconies,...,furnishing,floor,transaction_type,property_type,possession_status,ownership,facing,society,posted_by,url
0,85343819,3BHK Multistorey Apartment for Resale in Assot...,17000000.0,1.70 Cr,10272.0,Rudrapur,Bhubaneswar,3,3,NaN,...,Unfurnished,14 of 14 Floor,Resale,Apartment,Ready to Move,NaN,NaN,Assotech Pride,Owner,https://www.magicbricks.com/propertyDetails-3-...
1,85324987,3BHK Multistorey Apartment for Resale in,14900000.0,1.49 Cr,11920.0,NaN,Bhubaneswar,3,2,2.0,...,Unfurnished,Ground of 3 Floor,Resale,Apartment,Ready to Move,Leasehold,South,NaN,Owner,https://www.magicbricks.com/propertyDetails-3-...
2,85331583,3BHK Multistorey Apartment for Resale in DN Fa...,14000000.0,1.40 Cr,8669.0,Madanpur,Bhubaneswar,3,2,2.0,...,Semi-Furnished,5 of 14 Floor,Resale,Apartment,Ready to Move,Freehold,NaN,DN Fairytale,Owner,https://www.magicbricks.com/propertyDetails-3-...
3,85326997,3BHK Multistorey Apartment for Resale in Pokha...,12500000.0,1.25 Cr,9615.0,Pokhariput,Bhubaneswar,3,3,1.0,...,Semi-Furnished,2 of 4 Floor,Resale,Apartment,Ready to Move,Freehold,NaN,NaN,Owner,https://www.magicbricks.com/propertyDetails-3-...
4,51858951,Residential Plot for New Property in Patrapada,1650000.0,16.5 Lac,1100.0,Patrapada,Bhubaneswar,NaN,NaN,NaN,...,NaN,NaN,New Property,Residential Plot,NaN,Freehold,North - East,NaN,Owner,https://www.magicbricks.com/propertyDetails-15...

In [4]:
df.columns

Index(['id', 'title', 'price', 'price_display', 'price_per_sqft', 'locality',
       'city', 'bhk', 'bathrooms', 'balconies', 'area_sqft', 'carpet_area',
       'furnishing', 'floor', 'transaction_type', 'property_type',
       'possession_status', 'ownership', 'facing', 'society', 'posted_by',
       'url'],
      dtype='str')

In [5]:
df.shape

(1752, 22)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1752 entries, 0 to 1751
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1752 non-null   int64
 1   title              1752 non-null   str
 2   price              1713 non-null   float64
 3   price_display      1752 non-null   str
 4   price_per_sqft     1678 non-null   float64
 5   locality           1682 non-null   str
 6   city               1752 non-null   str
 7   bhk                1308 non-null   str
 8   bathrooms          1286 non-null   str
 9   balconies          1051 non-null   float64
 10  area_sqft          1271 non-null   float64
 11  carpet_area        771 non-null    float64
 12  furnishing         1238 non-null   str
 13  floor              845 non-null    str
 14  transaction_type   1750 non-null   str
 15  property_type      1752 non-null   str
 16  possession_status  1279 non-null   str
 17  ownership          905 non-null    str
 18  facing             885 non-null    str
 19  society            797 non-null    str
 20  posted_by          1752 non-null   str
 21  url                1752 non-null   str
dtypes: float64(5), int64(1), str(16)
memory usage: 301.3 KB

In [7]:
df.describe()

,id,price,price_per_sqft,balconies,area_sqft,carpet_area
count,1.752000e+03,1.713000e+03,1678.000000,1051.000000,1271.000000,771.000000
mean,7.922105e+07,1.313827e+07,6200.453516,2.067555,1889.321007,1469.582361
std,9.025151e+06,1.337889e+07,3922.109068,0.948283,902.968502,4468.946913
min,2.675089e+07,2.500000e+05,0.000000,1.000000,500.000000,194.000000
25%,7.753989e+07,6.100000e+06,4000.000000,1.000000,1369.000000,956.000000
50%,8.343802e+07,1.000000e+07,6111.000000,2.000000,1700.000000,1147.000000
75%,8.484611e+07,1.575600e+07,8009.000000,3.000000,2169.000000,1448.500000
max,8.534525e+07,2.040000e+08,73333.000000,10.000000,12000.000000,123740.000000

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
# Row(s) with the suspicious carpet_area outlier
df[df['carpet_area'] == df['carpet_area'].max()]

,id,title,price,price_display,price_per_sqft,locality,city,bhk,bathrooms,balconies,...,furnishing,floor,transaction_type,property_type,possession_status,ownership,facing,society,posted_by,url
626,84973541,3BHK Multistorey Apartment for New Property in...,10732100.0,1.07 Cr,5900.0,Hans Pal,Bhubaneswar,3,3,2.0,...,Unfurnished,2 of 3 Floor,New Property,Apartment,Ready to Move,Freehold,South - East,NaN,Agent,https://www.magicbricks.com/propertyDetails-3-...

In [10]:
# Rows where price_per_sqft is exactly 0
df[df['price_per_sqft'] == 0]

,id,title,price,price_display,price_per_sqft,locality,city,bhk,bathrooms,balconies,...,furnishing,floor,transaction_type,property_type,possession_status,ownership,facing,society,posted_by,url
427,79169473,Residential Plot for Resale in Infogreen City...,2400000.0,24 Lac,0.0,Mendhasala,Bhubaneswar,NaN,NaN,NaN,...,NaN,NaN,Resale,Residential Plot,NaN,NaN,NaN,Infogreen City,Owner,https://www.magicbricks.com/propertyDetails-12...
959,83383029,Residential Plot for Resale in,250000.0,2.5 Lac,0.0,NaN,Bhubaneswar,NaN,NaN,NaN,...,NaN,NaN,Resale,Residential Plot,NaN,NaN,NaN,NaN,Owner,https://www.magicbricks.com/propertyDetails-98...

In [11]:
# Display the top 10 properties with the largest carpet area

df.sort_values("carpet_area", ascending=False)[
    ["title", "property_type", "area_sqft", "carpet_area", "price", "locality"]
].head(10)

,title,property_type,area_sqft,carpet_area,price,locality
626,3BHK Multistorey Apartment for New Property in...,Apartment,1819.0,123740.0,10732100.0,Hans Pal
13,3BHK Multistorey Apartment for New Property in...,Apartment,NaN,11320.0,16600000.0,Rudrapur
912,> 10BHK Residential House for Resale in Ekamra...,Residential House,7100.0,6100.0,70000000.0,Jayadev Vihar
648,2BHK Builder Floor Apartment for Resale in,Builder Floor Apartment,NaN,6000.0,45000000.0,NaN
1453,9BHK Builder Floor Apartment for New Property ...,Builder Floor Apartment,6500.0,5800.0,22000000.0,Khandagiri
1569,6BHK Residential House for Resale in Phase 2 P...,Residential House,3000.0,5500.0,36000000.0,Phase 2 Patia
611,3BHK Residential House for New Property in Bad...,Residential House,2100.0,5200.0,28900000.0,Badaraghunathpur
116,10BHK Villa for Resale in IRC Village,Villa,6000.0,5000.0,167500000.0,IRC Village
1379,Residential House for Resale in Tankapani Road,Residential House,3000.0,4500.0,40000000.0,Tankapani Road
1559,5BHK Residential House for Resale in Phulnakhara,Residential House,4600.0,3600.0,50000000.0,Phulnakhara

In [12]:
# Find properties where the scraped price_per_sqft is zero.

df[df["price_per_sqft"] == 0][
    ["title", "price", "area_sqft", "price_per_sqft", "property_type"]
]

,title,price,area_sqft,price_per_sqft,property_type
427,Residential Plot for Resale in Infogreen City...,2400000.0,NaN,0.0,Residential Plot
959,Residential Plot for Resale in,250000.0,NaN,0.0,Residential Plot

In [13]:
# Display properties where the BHK value is missing.

df[df["bhk"].isna()][
    ["title", "property_type", "area_sqft", "price"]
].head(20)

,title,property_type,area_sqft,price
4,Residential Plot for New Property in Patrapada,Residential Plot,NaN,1650000.0
5,Residential Plot for Resale in Aiims Valley a...,Residential Plot,NaN,2475000.0
10,Residential Plot for Resale in Utkal Jyoti En...,Residential Plot,NaN,4000000.0
16,Residential Plot for Resale in Dumduma,Residential Plot,NaN,150000000.0
21,Residential Plot for Resale in Sahaspur,Residential Plot,NaN,1800000.0
26,Residential Plot for Resale in Patrapada,Residential Plot,NaN,1700000.0
30,Residential Plot for Resale in Info valley at...,Residential Plot,NaN,3600000.0
35,Residential Plot for New Property in Balakati,Residential Plot,NaN,15688800.0
42,Residential Plot for Resale in Pahala,Residential Plot,NaN,5100000.0
43,Residential Plot for New Property in Patia,Residential Plot,NaN,1650000.0
56,Residential Plot for Resale in Koradakanta,Residential Plot,NaN,4200000.0
57,Residential Plot for Resale in Chandaka,Residential Plot,NaN,11400000.0
58,Residential Plot for Resale in Kapila Prasad,Residential Plot,NaN,14500000.0
61,Residential Plot for Resale in Ebaranga,Residential Plot,NaN,10000000.0
66,Residential Plot for Resale in Arugul Railway...,Residential Plot,NaN,500000.0
71,Residential Plot for Resale in Phulnakhara,Residential Plot,NaN,16500000.0
73,Residential Plot for Resale in Raghunathpur,Residential Plot,NaN,14790000.0
76,Residential Plot for Resale in Balakati,Residential Plot,NaN,1200000.0
78,Residential Plot for Resale in Mahura,Residential Plot,NaN,4200000.0
79,Residential Plot for Resale in Ranga Bazar,Residential Plot,NaN,3000000.0

In [21]:
# Display properties with missing area_sqft values.

df[df["area_sqft"].isna()][
    ["title", "property_type", "price", "bhk"]
]

,title,property_type,price,bhk
4,Residential Plot for New Property in Patrapada,Residential Plot,1650000.0,NaN
5,Residential Plot for Resale in Aiims Valley a...,Residential Plot,2475000.0,NaN
10,Residential Plot for Resale in Utkal Jyoti En...,Residential Plot,4000000.0,NaN
13,3BHK Multistorey Apartment for New Property in...,Apartment,16600000.0,3
16,Residential Plot for Resale in Dumduma,Residential Plot,150000000.0,NaN
...,...,...,...,...
1734,Residential Plot for Resale in Nayapalli,Residential Plot,90000000.0,NaN
1737,Residential Plot for Resale in Daruthenga,Residential Plot,4000000.0,NaN
1745,4BHK Villa for New Property in Jatani,Villa,15400000.0,4
1748,Residential Plot for Resale in Badaraghunathpur,Residential Plot,11900000.0,NaN
1751,Residential Plot for Resale in Info Colony II...,Residential Plot,3000000.0,NaN

In [15]:
# Generate summary statistics for the price column

df["price"].describe()

count    1.713000e+03
mean     1.313827e+07
std      1.337889e+07
min      2.500000e+05
25%      6.100000e+06
50%      1.000000e+07
75%      1.575600e+07
max      2.040000e+08
Name: price, dtype: float64

In [16]:
# Display the 10 cheapest properties.

df.nsmallest(10, "price")[
    ["title", "price", "property_type", "area_sqft"]
]

,title,price,property_type,area_sqft
959,Residential Plot for Resale in,250000.0,Residential Plot,NaN
557,Residential Plot for Resale in Patia,399999.0,Residential Plot,NaN
913,Residential Plot for Resale in Sundarpada,400000.0,Residential Plot,NaN
815,Residential Plot for Resale in Khordha,420000.0,Residential Plot,NaN
1309,Residential Plot for New Property in Khordha,420000.0,Residential Plot,NaN
66,Residential Plot for Resale in Arugul Railway...,500000.0,Residential Plot,NaN
201,Residential Plot for Resale in Tankapani Road,720000.0,Residential Plot,NaN
1317,Residential Plot for New Property in Sai Para...,720000.0,Residential Plot,NaN
1273,Residential Plot for Resale in Uttara,800000.0,Residential Plot,NaN
1304,Residential Plot for Resale in Patia,800000.0,Residential Plot,NaN

In [17]:
# Display the 10 most expensive properties.

df.nlargest(10, "price")[
    ["title", "price", "property_type", "area_sqft"]
]

,title,price,property_type,area_sqft
652,Residential Plot for Resale in bda housing pr...,204000000.0,Residential Plot,NaN
116,10BHK Villa for Resale in IRC Village,167500000.0,Villa,6000.0
16,Residential Plot for Resale in Dumduma,150000000.0,Residential Plot,NaN
1277,Residential House for Resale in Master Cantee...,150000000.0,Residential House,6060.0
1324,Residential Plot for Resale in Sahid Nagar,110000000.0,Residential Plot,NaN
1514,Residential Plot for Resale in BJB Nagar,110000000.0,Residential Plot,NaN
653,Residential Plot for Resale in Saheed Nagar,97000000.0,Residential Plot,NaN
1252,> 10BHK Builder Floor Apartment for Resale in ...,90000000.0,Builder Floor Apartment,12000.0
1734,Residential Plot for Resale in Nayapalli,90000000.0,Residential Plot,NaN
1254,10BHK Residential House for Resale in,75000000.0,Residential House,3767.0

In [18]:
# Count duplicate URLs.

df["url"].duplicated().sum()

np.int64(0)

In [19]:
# Count duplicate IDs.

df["id"].duplicated().sum()

np.int64(0)

In [22]:
# Count missing BHK by property type
df[df["bhk"].isna()]["property_type"].value_counts()

property_type
Residential Plot           423
Apartment                    9
Residential House            9
Studio Apartment             2
Builder Floor Apartment      1
Name: count, dtype: int64

In [23]:
# Count missing area by property type
df[df["area_sqft"].isna()]["property_type"].value_counts()

property_type
Residential Plot           423
Apartment                   35
Residential House           11
Villa                        9
Builder Floor Apartment      3
Name: count, dtype: int64

In [25]:
# Create a copy of the original dataset
raw_df = df.copy()

In [26]:
# Convert column names to lowercase and replace spaces with underscores
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [27]:
# Remove extra spaces from all string columns
for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip()

C:\Users\91889\AppData\Local\Temp\ipykernel_4884\3561479356.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object"):

In [28]:
df.dtypes

id                     int64
title                    str
price                float64
price_display            str
price_per_sqft       float64
locality                 str
city                     str
bhk                      str
bathrooms                str
balconies            float64
area_sqft            float64
carpet_area          float64
furnishing               str
floor                    str
transaction_type         str
property_type            str
possession_status        str
ownership                str
facing                   str
society                  str
posted_by                str
url                      str
dtype: object

In [29]:
# Check for common string representations of missing values
missing_values = ["NA", "N/A", "None", "-", "", "null"]

for value in missing_values:
    print(f"\nChecking for '{value}':")
    print((df == value).sum().sum())

Checking for 'NA':
0

Checking for 'N/A':
0

Checking for 'None':
0

Checking for '-':
0

Checking for '':
0

Checking for 'null':
0

##### Cleaning the target Variable

In [30]:
# Count missing values in the price column
df["price"].isna().sum()

np.int64(39)

In [31]:
# Display properties with missing prices
df[df["price"].isna()][
    ["title", "property_type", "area_sqft", "bhk", "locality"]
]

,title,property_type,area_sqft,bhk,locality
206,Multistorey Apartment for Resale in Dream Gymk...,Apartment,NaN,NaN,Sham Pur
249,2BHK Residential House for Resale in Patia,Residential House,500.0,2,Patia
295,Multistorey Apartment for Resale in SBI Colony...,Apartment,NaN,NaN,Kesora
332,Residential Plot for Resale in Jatani,Residential Plot,NaN,NaN,Jatani
374,2BHK Builder Floor Apartment for Resale in Unit 8,Builder Floor Apartment,1100.0,2,Unit 8
406,3BHK Residential House in Acharya Vihar,Residential House,2000.0,3,Acharya Vihar
425,Multistorey Apartment for Resale in Khordha,Apartment,NaN,NaN,Khordha
472,Multistorey Apartment for Resale in Assotech P...,Apartment,NaN,NaN,Rudrapur
701,Multistorey Apartment for Resale in Kalyani Pl...,Apartment,NaN,NaN,Sundarpada
722,3BHK Multistorey Apartment for Resale in Chand...,Apartment,NaN,3,Chandrasekharpur
724,2BHK Multistorey Apartment for Resale in Jagan...,Apartment,936.0,2,Madanpur
790,3BHK Multistorey Apartment for Resale in Nages...,Apartment,1750.0,3,Patia
819,6BHK Residential House in Haridaspur,Residential House,3000.0,6,Haridaspur
820,Residential House for Resale in,Residential House,NaN,NaN,NaN
863,Residential Plot for Resale in Andharua,Residential Plot,NaN,NaN,Andharua
935,Residential Plot for Resale in Khordha,Residential Plot,NaN,NaN,Khordha
939,1BHK Multistorey Apartment for Resale in Akank...,Apartment,521.0,1,Gothapatna
963,Residential House for Resale in Kausalya Ganga,Residential House,NaN,NaN,Kausalya Ganga
971,Residential Plot for Resale in Ranga Bazar,Residential Plot,NaN,NaN,Ranga Bazar
987,Residential House for Resale in,Residential House,NaN,NaN,NaN
1042,3BHK Multistorey Apartment for Resale in Sahid...,Apartment,1480.0,3,Sahid Nagar
1051,Multistorey Apartment for Resale in Supratik E...,Apartment,NaN,NaN,Jagamara
1071,2BHK Multistorey Apartment for New Property in...,Apartment,1185.0,2,Tamando
1072,Residential House for Resale in Madanpur,Residential House,NaN,NaN,Madanpur
1114,Residential House for Resale in Daruthenga,Residential House,NaN,NaN,Daruthenga
1180,2BHK Residential House for Resale in A V Resid...,Residential House,1300.0,2,Patia
1235,Multistorey Apartment for Resale in IRC Village,Apartment,NaN,NaN,IRC Village
1263,Residential House for Resale in prestige resid...,Residential House,NaN,NaN,Jharapara
1267,4BHK Residential House for New Property in Mas...,Residential House,1900.0,4,Master Canteen Chowk
1316,2BHK Multistorey Apartment for Resale in Nilad...,Apartment,NaN,2,Niladri Nagar
1327,Residential Plot for Resale in Pandra,Residential Plot,NaN,NaN,Pandra
1365,Residential Plot for Resale in Siula PIPLI,Residential Plot,NaN,NaN,Siula PIPLI
1369,Multistorey Apartment for Resale in Utkal Gree...,Apartment,2163.0,NaN,Sundarpada
1383,Builder Floor Apartment for Resale in,Builder Floor Apartment,NaN,NaN,NaN
1527,Residential House for Resale in Kalinga Nagar,Residential House,NaN,NaN,Kalinga Nagar
1566,2BHK Multistorey Apartment for Resale in,Apartment,900.0,2,NaN
1610,1BHK Residential House for Resale in Satya Vihar,Residential House,800.0,1,Satya Vihar
1638,4BHK Villa for Resale in Nakhara City at Phuln...,Villa,NaN,4,Phulnakhara
1714,2BHK Multistorey Apartment for New Property in...,Apartment,1185.0,2,Tamando

In [32]:
# Count properties with zero or negative prices
df[df["price"] <= 0]

Empty DataFrame
Columns: [id, title, price, price_display, price_per_sqft, locality, city, bhk, bathrooms, balconies, area_sqft, carpet_area, furnishing, floor, transaction_type, property_type, possession_status, ownership, facing, society, posted_by, url]
Index: []

[0 rows x 22 columns]

In [33]:
# Remove properties where the target variable (price) is missing
df = df.dropna(subset=["price"])

In [34]:
# Check that there are no missing values left in the price column
df["price"].isna().sum()

np.int64(0)

In [ ]:
# Display the updated dataset dimensions
print(df.shape)